### ISSUE TITLE
An option to disable tweak when long pressing emojis

### ISSUE THREAD

**Issue by NguyenASang** [r-plus/AnyKeyTrackpad#1]
Hi, thanks for your great tweak @r-plus. I would like to add 1 feature that would be useful if added.
Watch this video:

https://user-images.githubusercontent.com/87893636/160527117-3f5804d3-ea15-4894-99bf-c99ef71afb9a.MP4

As you can see in the video, sometimes I want to change the color of the icon. To do that, I need to long press the emoji, but when I do that, it triggers this tweak. So I want this tweak to only work on the bottom bar of the emoji keyboard and not when long pressing the emoji. That's all, thank you for reading.

**Comment by r-plus** [comment]
Sound good!
I’ll work for it when support to iOS 15 (soon?)

**Comment by NguyenASang** [comment]
> Sound good! I’ll work for it when support to iOS 15 (soon?)

I think the jailbreak for iOS 15 will be released soon. Thanks in advance.

**Comment by NguyenASang** [comment]
@r-plus Hey, this one too:)

**Comment by NguyenASang** [comment]
@r-plus I have some serious problems with my phone so I can't test the latest version now. 

Also option to disable "Accented Variant Keys" pop-up only works properly if you don't type anything.

How to reproduce this:
Case 1: _**Don't type**_ anything and _**hold on key that has other accented keys**_ 
→ The pop-up _**doesn't appear**_.

Case 2: _**Type something**_ and _**hold on key that has other accented keys**_ 
→ The pop-up **_appears but will be removed afterward_**.

**Comment by r-plus** [comment]
I cannot reproduce it on iOS 15.

emoji option that talking on this issue is available on v1.1.
